// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: catservice.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatService_GetCatById_FullMethodName = "/catservice.CatService/GetCatById"
	CatService_GetAllCats_FullMethodName = "/catservice.CatService/GetAllCats"
	CatService_CreateCat_FullMethodName  = "/catservice.CatService/CreateCat"
)

// CatServiceClient is the client API for CatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatServiceClient interface {
	GetCatById(ctx context.Context, in *GetCatByIdRequest, opts ...grpc.CallOption) (*GetCatByIdResponse, error)
	GetAllCats(ctx context.Context, in *GetAllCatsRequest, opts ...grpc.CallOption) (*GetAllCatsResponse, error)
	CreateCat(ctx context.Context, in *CreateCatRequest, opts ...grpc.CallOption) (*CreateCatResponse, error)
}

type catServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatServiceClient(cc grpc.ClientConnInterface) CatServiceClient {
	return &catServiceClient{cc}
}

func (c *catServiceClient) GetCatById(ctx context.Context, in *GetCatByIdRequest, opts ...grpc.CallOption) (*GetCatByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatByIdResponse)
	err := c.cc.Invoke(ctx, CatService_GetCatById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetAllCats(ctx context.Context, in *GetAllCatsRequest, opts ...grpc.CallOption) (*GetAllCatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCatsResponse)
	err := c.cc.Invoke(ctx, CatService_GetAllCats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CreateCat(ctx context.Context, in *CreateCatRequest, opts ...grpc.CallOption) (*CreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_CreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServiceServer is the server API for CatService service.
// All implementations must embed UnimplementedCatServiceServer
// for forward compatibility.
type CatServiceServer interface {
	GetCatById(context.Context, *GetCatByIdRequest) (*GetCatByIdResponse, error)
	GetAllCats(context.Context, *GetAllCatsRequest) (*GetAllCatsResponse, error)
	CreateCat(context.Context, *CreateCatRequest) (*CreateCatResponse, error)
	mustEmbedUnimplementedCatServiceServer()
}

// UnimplementedCatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatServiceServer struct{}

func (UnimplementedCatServiceServer) GetCatById(context.Context, *GetCatByIdRequest) (*GetCatByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatById not implemented")
}
func (UnimplementedCatServiceServer) GetAllCats(context.Context, *GetAllCatsRequest) (*GetAllCatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCats not implemented")
}
func (UnimplementedCatServiceServer) CreateCat(context.Context, *CreateCatRequest) (*CreateCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCat not implemented")
}
func (UnimplementedCatServiceServer) mustEmbedUnimplementedCatServiceServer() {}
func (UnimplementedCatServiceServer) testEmbeddedByValue()                    {}

// UnsafeCatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatServiceServer will
// result in compilation errors.
type UnsafeCatServiceServer interface {
	mustEmbedUnimplementedCatServiceServer()
}

func RegisterCatServiceServer(s grpc.ServiceRegistrar, srv CatServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatService_ServiceDesc, srv)
}

func _CatService_GetCatById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetCatById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetCatById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetCatById(ctx, req.(*GetCatByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetAllCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetAllCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetAllCats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetAllCats(ctx, req.(*GetAllCatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CreateCat(ctx, req.(*CreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatService_ServiceDesc is the grpc.ServiceDesc for CatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catservice.CatService",
	HandlerType: (*CatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatById",
			Handler:    _CatService_GetCatById_Handler,
		},
		{
			MethodName: "GetAllCats",
			Handler:    _CatService_GetAllCats_Handler,
		},
		{
			MethodName: "CreateCat",
			Handler:    _CatService_CreateCat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catservice.proto",
}
